# Auto-generated by asn1ate v.0.6.0 from UserInfo.asn1
# (last modified on 2018-04-26 14:00:10.063795)

from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


class UserInfo(univ.Sequence):
    pass


UserInfo.componentType = namedtype.NamedTypes(
    namedtype.NamedType('userID', univ.OctetString()),
    namedtype.NamedType('userName', univ.OctetString()),
    namedtype.NamedType('password', univ.OctetString()),
    namedtype.NamedType('age', univ.Integer())
)


