package javacc;
/* Generated By:JJTree: Do not edit this line. ASTAssignmentList.java */

public class ASTAssignmentList extends SimpleNode {
  public ASTAssignmentList(int id) {
    super(id);
  }

  public ASTAssignmentList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
