package javacc;
/* Generated By:JJTree: Do not edit this line. ASTAssignedIdentifier.java */

public class ASTAssignedIdentifier extends SimpleNode {
  public ASTAssignedIdentifier(int id) {
    super(id);
  }

  public ASTAssignedIdentifier(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
