package javacc;
/* Generated By:JJTree: Do not edit this line. ASTAnyType.java */

public class ASTAnyType extends SimpleNode {
  public ASTAnyType(int id) {
    super(id);
  }

  public ASTAnyType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
