package javacc;
/* Generated By:JJTree: Do not edit this line. ASTBuiltinValue.java */

public class ASTBuiltinValue extends SimpleNode {
  public ASTBuiltinValue(int id) {
    super(id);
  }

  public ASTBuiltinValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
