package javacc;
/* Generated By:JJTree: Do not edit this line. ASTBooleanValue.java */

public class ASTBooleanValue extends SimpleNode {
  public ASTBooleanValue(int id) {
    super(id);
  }

  public ASTBooleanValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
