package javacc;
/* Generated By:JJTree: Do not edit this line. ASTContainedSubtype.java */

public class ASTContainedSubtype extends SimpleNode {
  public ASTContainedSubtype(int id) {
    super(id);
  }

  public ASTContainedSubtype(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
