package javacc;
/* Generated By:JJTree: Do not edit this line. ASTClass.java */

public class ASTClass extends SimpleNode {

	private int tc = ASTTaggedType.CONTEXT;

	public void
	setTagClass(int x)
	{
		tc = x;
	}

	public int
	getTagClass()
	{
		return tc;
	}

  public ASTClass(int id) {
    super(id);
  }

  public ASTClass(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
