package javacc;
/* Generated By:JJTree: Do not edit this line. ASTConstraint.java */

public class ASTConstraint extends SimpleNode {
  public ASTConstraint(int id) {
    super(id);
  }

  public ASTConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
