package javacc;
/* Generated By:JJTree: Do not edit this line. ASTDefinedMacroName.java */

public class ASTDefinedMacroName extends SimpleNode {
  public ASTDefinedMacroName(int id) {
    super(id);
  }

  public ASTDefinedMacroName(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
