package javacc;
/* Generated By:JJTree: Do not edit this line. ASTDefinedMacroType.java */

public class ASTDefinedMacroType extends SimpleNode {
  public ASTDefinedMacroType(int id) {
    super(id);
  }

  public ASTDefinedMacroType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
