package javacc;
/* Generated By:JJTree: Do not edit this line. ASTDisplayHint.java */

public class ASTDisplayHint extends SimpleNode {
  public ASTDisplayHint(int id) {
    super(id);
  }

  public ASTDisplayHint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
