package javacc;
/* Generated By:JJTree: Do not edit this line. ASTDefinedValue.java */

public class ASTDefinedValue extends SimpleNode {
  public ASTDefinedValue(int id) {
    super(id);
  }

  public ASTDefinedValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
