package javacc;
import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.util.Vector;

/* Generated By:JJTree: Do not edit this line. ASTEnumeratedType.java */

public class ASTEnumeratedType extends SimpleNode {
  public ASTEnumeratedType(int id) {
    super(id);
  }

  public ASTEnumeratedType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
}
