package javacc;
/* Generated By:JJTree: Do not edit this line. ASTExports.java */

public class ASTExports extends SimpleNode {
  public ASTExports(int id) {
    super(id);
  }

  public ASTExports(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
