package javacc;
/* Generated By:JJTree: Do not edit this line. ASTInnerTypeConstraints.java */

public class ASTInnerTypeConstraints extends SimpleNode {
  public ASTInnerTypeConstraints(int id) {
    super(id);
  }

  public ASTInnerTypeConstraints(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
