package javacc;
/* Generated By:JJTree: Do not edit this line. ASTmodulereference.java */

public class ASTmodulereference extends SimpleNode {
  public ASTmodulereference(int id) {
    super(id);
  }

  public ASTmodulereference(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
