package javacc;
/* Generated By:JJTree: Do not edit this line. ASTMacroDefinition.java */

public class ASTMacroDefinition extends SimpleNode {
  public ASTMacroDefinition(int id) {
    super(id);
  }

  public ASTMacroDefinition(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
