package javacc;
/* Generated By:JJTree: Do not edit this line. ASTModuleDefinition.java */

public class ASTModuleDefinition extends SimpleNode {
  public ASTModuleDefinition(int id) {
    super(id);
  }

  public ASTModuleDefinition(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
