package javacc;
/* Generated By:JJTree: Do not edit this line. ASTModuleBody.java */

public class ASTModuleBody extends SimpleNode {
  public ASTModuleBody(int id) {
    super(id);
  }

  public ASTModuleBody(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
