package javacc;
/* Generated By:JJTree: Do not edit this line. ASTModuleIdentifier.java */

public class ASTModuleIdentifier extends SimpleNode {
  public ASTModuleIdentifier(int id) {
    super(id);
  }

  public ASTModuleIdentifier(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
