package javacc;
/* Generated By:JJTree: Do not edit this line. ASTMultipleTypeConstraints.java */

public class ASTMultipleTypeConstraints extends SimpleNode {
  public ASTMultipleTypeConstraints(int id) {
    super(id);
  }

  public ASTMultipleTypeConstraints(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
