package javacc;
/* Generated By:JJTree: Do not edit this line. ASTNamedNumberList.java */

public class ASTNamedNumberList extends SimpleNode {
  public ASTNamedNumberList(int id) {
    super(id);
  }

  public ASTNamedNumberList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
