package javacc;
/* Generated By:JJTree: Do not edit this line. ASTNumberForm.java */

public class ASTNumberForm extends SimpleNode {
  public ASTNumberForm(int id) {
    super(id);
  }

  public ASTNumberForm(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
