package javacc;
/* Generated By:JJTree: Do not edit this line. ASTNamedConstraint.java */

public class ASTNamedConstraint extends SimpleNode {
  public ASTNamedConstraint(int id) {
    super(id);
  }

  public ASTNamedConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
