package javacc;

import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
/* Generated By:JJTree: Do not edit this line. ASTNullType.java */

public class ASTNullType extends SimpleNode {
  public ASTNullType(int id) {
    super(id);
  }

  public ASTNullType(AsnParser p, int id) {
    super(p, id);
  }
  
  ///////////////////////////
  // Added by Fatih Batuk
  // generateClass() method is necessary for creation of Null objects
	
  public void
	generateClass(String name)
	{
		try
		{
			InputStream is = getClass().getResourceAsStream("null.template");	
			String templateName = "null.template";		
			String filename = null;
			if(AsnParser.outputDirectory != null)
				filename = new String(AsnParser.outputDirectory + System.getProperty("file.separator") + name + ".java");
			else
				filename = new String(name + ".java");

			OutputStream os = new FileOutputStream(filename);
			BufferedReader reader = new BufferedReader(new FileReader(templateName)); 
			String line;
			while(true)
			{
				line = reader.readLine();
				if(line == null)
					break;

				while(true)
				{
					int idx = line.indexOf('@');
					if(idx == -1)
						break;

					int ndx = line.indexOf('@', idx + 1);	// look for the closing symbol
					if(ndx == -1)
						break;

					String directive = line.substring(idx + 1, ndx);
					if(directive.equals("name"))	// replace with the class name
					{
						String left = line.substring(0, idx);
						String right = line.substring(ndx + 1);
						line = new String(left + name + right);
						continue;
					}

					if(directive.equals("package"))	// insert a list of declarations
					{
						if(AsnParser.outputPackage != null)
							line = new String("package " + AsnParser.outputPackage + ";");
						else
							line = "";

						continue;
					}
				}

				os.write(line.getBytes());
				os.write(0x0a);
			}

			os.flush();
			os.close();
			reader.close();
		}
		catch(IOException e)
		{
			e.printStackTrace();
		}
	}

///////////////////////////////////////
	
	
  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
