package javacc;
/* Generated By:JJTree: Do not edit this line. ASTNullValue.java */

public class ASTNullValue extends SimpleNode {
  public ASTNullValue(int id) {
    super(id);
  }

  public ASTNullValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
