package javacc;
/* Generated By:JJTree: Do not edit this line. ASTNamedValue.java */

public class ASTNamedValue extends SimpleNode {
  public ASTNamedValue(int id) {
    super(id);
  }

  public ASTNamedValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
