package javacc;
/* Generated By:JJTree: Do not edit this line. ASTObjectIdentifierValue.java */

public class ASTObjectIdentifierValue extends SimpleNode {
  public ASTObjectIdentifierValue(int id) {
    super(id);
  }

  public ASTObjectIdentifierValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
