package javacc;
/* Generated By:JJTree: Do not edit this line. ASTObjIdComponentList.java */

public class ASTObjIdComponentList extends SimpleNode {
  public ASTObjIdComponentList(int id) {
    super(id);
  }

  public ASTObjIdComponentList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
