package javacc;
/* Generated By:JJTree: Do not edit this line. ASTOctetStringType.java */

public class ASTOctetStringType extends SimpleNode {
  public ASTOctetStringType(int id) {
    super(id);
  }

  public ASTOctetStringType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
