package javacc;
/* Generated By:JJTree: Do not edit this line. ASTPresenceConstraint.java */

public class ASTPresenceConstraint extends SimpleNode {
  public ASTPresenceConstraint(int id) {
    super(id);
  }

  public ASTPresenceConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
