package javacc;
/* Generated By:JJTree: Do not edit this line. ASTPermittedAlphabet.java */

public class ASTPermittedAlphabet extends SimpleNode {
  public ASTPermittedAlphabet(int id) {
    super(id);
  }

  public ASTPermittedAlphabet(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
