package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSingleValue.java */

public class ASTSingleValue extends SimpleNode {
  public ASTSingleValue(int id) {
    super(id);
  }

  public ASTSingleValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
