package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSpecialRealValue.java */

public class ASTSpecialRealValue extends SimpleNode {
  public ASTSpecialRealValue(int id) {
    super(id);
  }

  public ASTSpecialRealValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
