package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSizeConstraint.java */

public class ASTSizeConstraint extends SimpleNode {
  public ASTSizeConstraint(int id) {
    super(id);
  }

  public ASTSizeConstraint(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
