package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSubtypeValueSet.java */

public class ASTSubtypeValueSet extends SimpleNode {
  public ASTSubtypeValueSet(int id) {
    super(id);
  }

  public ASTSubtypeValueSet(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
