package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSnmpObjectTypeMacroType.java */

public class ASTSnmpObjectTypeMacroType extends SimpleNode {
  public ASTSnmpObjectTypeMacroType(int id) {
    super(id);
  }

  public ASTSnmpObjectTypeMacroType(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
