package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSnmpDefValPart.java */

public class ASTSnmpDefValPart extends SimpleNode {
  public ASTSnmpDefValPart(int id) {
    super(id);
  }

  public ASTSnmpDefValPart(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
