package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSymbolsFromModuleList.java */

public class ASTSymbolsFromModuleList extends SimpleNode {
  public ASTSymbolsFromModuleList(int id) {
    super(id);
  }

  public ASTSymbolsFromModuleList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
