package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSymbolList.java */

public class ASTSymbolList extends SimpleNode {
  public ASTSymbolList(int id) {
    super(id);
  }

  public ASTSymbolList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
