package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSymbol.java */

public class ASTSymbol extends SimpleNode {
  public ASTSymbol(int id) {
    super(id);
  }

  public ASTSymbol(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
