package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSymbolsExported.java */

public class ASTSymbolsExported extends SimpleNode {
  public ASTSymbolsExported(int id) {
    super(id);
  }

  public ASTSymbolsExported(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
