package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSubtypeValueSetList.java */

public class ASTSubtypeValueSetList extends SimpleNode {
  public ASTSubtypeValueSetList(int id) {
    super(id);
  }

  public ASTSubtypeValueSetList(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
