package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSymbolsImported.java */

public class ASTSymbolsImported extends SimpleNode {
  public ASTSymbolsImported(int id) {
    super(id);
  }

  public ASTSymbolsImported(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
