package javacc;
/* Generated By:JJTree: Do not edit this line. ASTSignedNumber.java */

public class ASTSignedNumber extends SimpleNode {
  public ASTSignedNumber(int id) {
    super(id);
  }

  public ASTSignedNumber(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
