package javacc;
/* Generated By:JJTree: Do not edit this line. ASTtypereference.java */

public class ASTtypereference extends SimpleNode {
  public ASTtypereference(int id) {
    super(id);
  }

  public ASTtypereference(AsnParser p, int id) {
    super(p, id);
  }


	public String
	toString()
	{
		return new String("typereference: " + first_token.image);
	}

	public String
	getClassName()
	{
		return first_token.image;
	}

  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
