package javacc;
/* Generated By:JJTree: Do not edit this line. ASTTag.java */

public class ASTTag extends SimpleNode {

	public int
	getTagNumber()
	{
		int numChildren = jjtGetNumChildren();
		for(int i = 0; i < numChildren; i++)
		{
			SimpleNode n = (SimpleNode)jjtGetChild(i);
			if(n instanceof ASTClassNumber)
				return ((ASTClassNumber)n).getTagNumber();
		}

		return -1;
	}

	public int
	getTagClass()
	{
		int numChildren = jjtGetNumChildren();
		for(int i = 0; i < numChildren; i++)
		{
			SimpleNode n = (SimpleNode)jjtGetChild(i);
			if(n instanceof ASTClass)
				return ((ASTClass)n).getTagClass();
		}

		return ASTTaggedType.CONTEXT;
	}

  public ASTTag(int id) {
    super(id);
  }

  public ASTTag(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
