package javacc;
/* Generated By:JJTree: Do not edit this line. ASTTypeAssignment.java */

public class ASTTypeAssignment extends SimpleNode {
  public ASTTypeAssignment(int id) {
    super(id);
  }

  public ASTTypeAssignment(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
