package javacc;
/* Generated By:JJTree: Do not edit this line. ASTTagDefault.java */

public class ASTTagDefault extends SimpleNode {
  public ASTTagDefault(int id) {
    super(id);
  }

  public ASTTagDefault(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
