package javacc;
/* Generated By:JJTree: Do not edit this line. ASTTypeOrValue.java */

public class ASTTypeOrValue extends SimpleNode {
  public ASTTypeOrValue(int id) {
    super(id);
  }

  public ASTTypeOrValue(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
