package javacc;
/* Generated By:JJTree: Do not edit this line. ASTValueAssignment.java */

public class ASTValueAssignment extends SimpleNode {
  public ASTValueAssignment(int id) {
    super(id);
  }

  public ASTValueAssignment(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
