package javacc;
/* Generated By:JJTree: Do not edit this line. ASTValueRange.java */

public class ASTValueRange extends SimpleNode {
  public ASTValueRange(int id) {
    super(id);
  }

  public ASTValueRange(AsnParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(AsnParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
