/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UserInfoModule"
 * 	found in "UserInfo.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_UserInfo_H_
#define	_UserInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UserInfo */
typedef struct UserInfo {
	OCTET_STRING_t	 userID;
	OCTET_STRING_t	 userName;
	OCTET_STRING_t	 password;
	long	 age;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UserInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UserInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _UserInfo_H_ */
#include <asn_internal.h>
