/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UserInfoModule"
 * 	found in "UserInfo.asn1"
 * 	`asn1c -fnative-types`
 */

#include "UserInfo.h"

static asn_TYPE_member_t asn_MBR_UserInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UserInfo, userID),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UserInfo, userName),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UserInfo, password),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"password"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UserInfo, age),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"age"
		},
};
static const ber_tlv_tag_t asn_DEF_UserInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UserInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, 0, 0 }, /* age */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 2 }, /* userID */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, -1, 1 }, /* userName */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, -2, 0 } /* password */
};
static asn_SEQUENCE_specifics_t asn_SPC_UserInfo_specs_1 = {
	sizeof(struct UserInfo),
	offsetof(struct UserInfo, _asn_ctx),
	asn_MAP_UserInfo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_UserInfo = {
	"UserInfo",
	"UserInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UserInfo_tags_1,
	sizeof(asn_DEF_UserInfo_tags_1)
		/sizeof(asn_DEF_UserInfo_tags_1[0]), /* 1 */
	asn_DEF_UserInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_UserInfo_tags_1)
		/sizeof(asn_DEF_UserInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_UserInfo_1,
	4,	/* Elements count */
	&asn_SPC_UserInfo_specs_1	/* Additional specs */
};

